### ISSUE TITLE
Cannot set a non-DockerHub registry as Docker Registry endpoint

### ISSUE THREAD

**Issue by djeeg** [Microsoft/VSTS-Docker-Preview#4]
I am trying to register a custom Docker Registry with VSTS

The custom registry is hosted on ACS(Swarm), installed using these instructions
https://docs.docker.com/registry/
The container is **registry:2**
https://hub.docker.com/_/registry/
The registry port has been mapped in the ACS agent load balancer and I have tested it is available by telnet

I can save the service with a URL like this
tcp://DEMOagents.westeurope.cloudapp.azure.com:5000

However when I reopen the service configuration, the URL has been reset to:
https://index.docker.io/v1/

Is this plugin locked to Docker Hub?

**Comment by RoopeshNair** [comment]
We're haven't validated it with ACS yet. Did you try using the service connection with Docker task? If yes, what errors do you see in the log?

Roopesh Nair
Sent using Phone
Excuse brevity, typos

**Comment by djeeg** [comment]
I have swapped my registry to a new azure VM with only a single docker engine running
And now I can save the custom registry with the configuration as dockerregistry.xyz.com:5000
(minus the tcp://)
